// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent.sql

package store

import (
	"context"
	"database/sql"
)

const countAgentDrafts = `-- name: CountAgentDrafts :one
SELECT COUNT(*) FROM agent_draft d JOIN question q ON q.id = d.question_id
WHERE d.conversation_id = ? AND q.status IN ('draft', 'needs_review', 'published')
`

// How many questions of a conversation are in play, the number the per-conversation cap counts.
func (q *Queries) CountAgentDrafts(ctx context.Context, conversationID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAgentDrafts, conversationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAgentDraft = `-- name: GetAgentDraft :one
SELECT d.question_id, d.conversation_id, d.lesson_id, d.device_id, d.verified, d.created_at, q.status
FROM agent_draft d JOIN question q ON q.id = d.question_id
WHERE d.question_id = ?
`

type GetAgentDraftRow struct {
	QuestionID     string `json:"question_id"`
	ConversationID string `json:"conversation_id"`
	LessonID       string `json:"lesson_id"`
	DeviceID       string `json:"device_id"`
	Verified       int64  `json:"verified"`
	CreatedAt      int64  `json:"created_at"`
	Status         string `json:"status"`
}

func (q *Queries) GetAgentDraft(ctx context.Context, questionID string) (GetAgentDraftRow, error) {
	row := q.db.QueryRowContext(ctx, getAgentDraft, questionID)
	var i GetAgentDraftRow
	err := row.Scan(
		&i.QuestionID,
		&i.ConversationID,
		&i.LessonID,
		&i.DeviceID,
		&i.Verified,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const insertAgentDraft = `-- name: InsertAgentDraft :exec
INSERT INTO agent_draft (question_id, conversation_id, lesson_id, device_id, verified, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertAgentDraftParams struct {
	QuestionID     string `json:"question_id"`
	ConversationID string `json:"conversation_id"`
	LessonID       string `json:"lesson_id"`
	DeviceID       string `json:"device_id"`
	Verified       int64  `json:"verified"`
	CreatedAt      int64  `json:"created_at"`
}

func (q *Queries) InsertAgentDraft(ctx context.Context, arg InsertAgentDraftParams) error {
	_, err := q.db.ExecContext(ctx, insertAgentDraft,
		arg.QuestionID,
		arg.ConversationID,
		arg.LessonID,
		arg.DeviceID,
		arg.Verified,
		arg.CreatedAt,
	)
	return err
}

const listAgentDrafts = `-- name: ListAgentDrafts :many
SELECT q.id, q.bank_id, q.chunk_id, q.type, q.stem, q.options, q.answer, q.explanation, q.difficulty, q.tags, q.source_quote, q.status, q.review_note, q.content_hash, q.gen_model, q.gen_prompt_version, q.flag_count, q.sync_seq, q.created_at, q.updated_at, d.conversation_id, d.verified
FROM agent_draft d JOIN question q ON q.id = d.question_id
WHERE d.conversation_id = ? AND q.status IN ('draft', 'needs_review', 'published')
ORDER BY d.created_at, q.id
`

type ListAgentDraftsRow struct {
	ID               string         `json:"id"`
	BankID           string         `json:"bank_id"`
	ChunkID          sql.NullString `json:"chunk_id"`
	Type             string         `json:"type"`
	Stem             string         `json:"stem"`
	Options          string         `json:"options"`
	Answer           string         `json:"answer"`
	Explanation      string         `json:"explanation"`
	Difficulty       int64          `json:"difficulty"`
	Tags             string         `json:"tags"`
	SourceQuote      string         `json:"source_quote"`
	Status           string         `json:"status"`
	ReviewNote       string         `json:"review_note"`
	ContentHash      string         `json:"content_hash"`
	GenModel         string         `json:"gen_model"`
	GenPromptVersion string         `json:"gen_prompt_version"`
	FlagCount        int64          `json:"flag_count"`
	SyncSeq          sql.NullInt64  `json:"sync_seq"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
	ConversationID   string         `json:"conversation_id"`
	Verified         int64          `json:"verified"`
}

// The questions of a conversation that are in play: waiting for a decision (older drafts) or adopted.
// Thrown-away ones are left out.
func (q *Queries) ListAgentDrafts(ctx context.Context, conversationID string) ([]ListAgentDraftsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAgentDrafts, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentDraftsRow{}
	for rows.Next() {
		var i ListAgentDraftsRow
		if err := rows.Scan(
			&i.ID,
			&i.BankID,
			&i.ChunkID,
			&i.Type,
			&i.Stem,
			&i.Options,
			&i.Answer,
			&i.Explanation,
			&i.Difficulty,
			&i.Tags,
			&i.SourceQuote,
			&i.Status,
			&i.ReviewNote,
			&i.ContentHash,
			&i.GenModel,
			&i.GenPromptVersion,
			&i.FlagCount,
			&i.SyncSeq,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ConversationID,
			&i.Verified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentQuestions = `-- name: ListAgentQuestions :many
SELECT id, bank_id, chunk_id, type, stem, options, answer, explanation, difficulty
FROM question
WHERE status = 'published'
ORDER BY created_at, id
`

type ListAgentQuestionsRow struct {
	ID          string         `json:"id"`
	BankID      string         `json:"bank_id"`
	ChunkID     sql.NullString `json:"chunk_id"`
	Type        string         `json:"type"`
	Stem        string         `json:"stem"`
	Options     string         `json:"options"`
	Answer      string         `json:"answer"`
	Explanation string         `json:"explanation"`
	Difficulty  int64          `json:"difficulty"`
}

// Every published question, for the assistant's tools.
func (q *Queries) ListAgentQuestions(ctx context.Context) ([]ListAgentQuestionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAgentQuestions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentQuestionsRow{}
	for rows.Next() {
		var i ListAgentQuestionsRow
		if err := rows.Scan(
			&i.ID,
			&i.BankID,
			&i.ChunkID,
			&i.Type,
			&i.Stem,
			&i.Options,
			&i.Answer,
			&i.Explanation,
			&i.Difficulty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttemptOutcomes = `-- name: ListAttemptOutcomes :many
SELECT question_id, is_correct, answered_at FROM attempt ORDER BY answered_at, id
`

type ListAttemptOutcomesRow struct {
	QuestionID string `json:"question_id"`
	IsCorrect  int64  `json:"is_correct"`
	AnsweredAt int64  `json:"answered_at"`
}

// Every answer ever given, oldest first, for the assistant's progress and weak-point tools.
func (q *Queries) ListAttemptOutcomes(ctx context.Context) ([]ListAttemptOutcomesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAttemptOutcomes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttemptOutcomesRow{}
	for rows.Next() {
		var i ListAttemptOutcomesRow
		if err := rows.Scan(&i.QuestionID, &i.IsCorrect, &i.AnsweredAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retireStaleDrafts = `-- name: RetireStaleDrafts :execrows
UPDATE question SET status = 'retired', review_note = 'auto: draft not handled in time', updated_at = ?
WHERE status = 'draft' AND id IN (SELECT d.question_id FROM agent_draft d WHERE d.created_at < ?)
`

type RetireStaleDraftsParams struct {
	UpdatedAt int64 `json:"updated_at"`
	CreatedAt int64 `json:"created_at"`
}

// Drafts nobody decided on for a while are taken out of the way. They stay in the table for the record.
func (q *Queries) RetireStaleDrafts(ctx context.Context, arg RetireStaleDraftsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, retireStaleDrafts, arg.UpdatedAt, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
