// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_attachment.sql

package store

import (
	"context"
	"database/sql"
)

const deleteConversationAttachments = `-- name: DeleteConversationAttachments :exec
DELETE FROM agent_attachment WHERE conversation_id = ?
`

func (q *Queries) DeleteConversationAttachments(ctx context.Context, conversationID string) error {
	_, err := q.db.ExecContext(ctx, deleteConversationAttachments, conversationID)
	return err
}

const deleteStaleAgentAttachments = `-- name: DeleteStaleAgentAttachments :execrows
DELETE FROM agent_attachment WHERE message_id IS NULL AND created_at < ?
`

// Files uploaded and never sent.
func (q *Queries) DeleteStaleAgentAttachments(ctx context.Context, createdAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteStaleAgentAttachments, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteUnsentAgentAttachment = `-- name: DeleteUnsentAgentAttachment :execrows
DELETE FROM agent_attachment WHERE id = ? AND message_id IS NULL
`

func (q *Queries) DeleteUnsentAgentAttachment(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUnsentAgentAttachment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAgentAttachment = `-- name: GetAgentAttachment :one
SELECT id, conversation_id, kind, name, mime, size, chars, width, height, text, data, message_id, created_at FROM agent_attachment WHERE id = ?
`

func (q *Queries) GetAgentAttachment(ctx context.Context, id string) (AgentAttachment, error) {
	row := q.db.QueryRowContext(ctx, getAgentAttachment, id)
	var i AgentAttachment
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Kind,
		&i.Name,
		&i.Mime,
		&i.Size,
		&i.Chars,
		&i.Width,
		&i.Height,
		&i.Text,
		&i.Data,
		&i.MessageID,
		&i.CreatedAt,
	)
	return i, err
}

const insertAgentAttachment = `-- name: InsertAgentAttachment :exec
INSERT INTO agent_attachment (id, conversation_id, kind, name, mime, size, chars, width, height, text, data, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAgentAttachmentParams struct {
	ID             string `json:"id"`
	ConversationID string `json:"conversation_id"`
	Kind           string `json:"kind"`
	Name           string `json:"name"`
	Mime           string `json:"mime"`
	Size           int64  `json:"size"`
	Chars          int64  `json:"chars"`
	Width          int64  `json:"width"`
	Height         int64  `json:"height"`
	Text           string `json:"text"`
	Data           []byte `json:"data"`
	CreatedAt      int64  `json:"created_at"`
}

func (q *Queries) InsertAgentAttachment(ctx context.Context, arg InsertAgentAttachmentParams) error {
	_, err := q.db.ExecContext(ctx, insertAgentAttachment,
		arg.ID,
		arg.ConversationID,
		arg.Kind,
		arg.Name,
		arg.Mime,
		arg.Size,
		arg.Chars,
		arg.Width,
		arg.Height,
		arg.Text,
		arg.Data,
		arg.CreatedAt,
	)
	return err
}

const listConversationAttachments = `-- name: ListConversationAttachments :many
SELECT id, conversation_id, kind, name, mime, size, chars, width, height, message_id, created_at
FROM agent_attachment WHERE conversation_id = ? ORDER BY created_at, id
`

type ListConversationAttachmentsRow struct {
	ID             string        `json:"id"`
	ConversationID string        `json:"conversation_id"`
	Kind           string        `json:"kind"`
	Name           string        `json:"name"`
	Mime           string        `json:"mime"`
	Size           int64         `json:"size"`
	Chars          int64         `json:"chars"`
	Width          int64         `json:"width"`
	Height         int64         `json:"height"`
	MessageID      sql.NullInt64 `json:"message_id"`
	CreatedAt      int64         `json:"created_at"`
}

// Without the text and the bytes: this is for lists and checks.
func (q *Queries) ListConversationAttachments(ctx context.Context, conversationID string) ([]ListConversationAttachmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listConversationAttachments, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationAttachmentsRow{}
	for rows.Next() {
		var i ListConversationAttachmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Kind,
			&i.Name,
			&i.Mime,
			&i.Size,
			&i.Chars,
			&i.Width,
			&i.Height,
			&i.MessageID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAgentAttachmentSent = `-- name: MarkAgentAttachmentSent :execrows
UPDATE agent_attachment SET message_id = ? WHERE id = ? AND conversation_id = ? AND message_id IS NULL
`

type MarkAgentAttachmentSentParams struct {
	MessageID      sql.NullInt64 `json:"message_id"`
	ID             string        `json:"id"`
	ConversationID string        `json:"conversation_id"`
}

func (q *Queries) MarkAgentAttachmentSent(ctx context.Context, arg MarkAgentAttachmentSentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markAgentAttachmentSent, arg.MessageID, arg.ID, arg.ConversationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
