// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_history.sql

package store

import (
	"context"
	"database/sql"
)

const deleteAgentConversation = `-- name: DeleteAgentConversation :exec
DELETE FROM agent_conversation WHERE id = ?
`

func (q *Queries) DeleteAgentConversation(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAgentConversation, id)
	return err
}

const deleteAgentMessages = `-- name: DeleteAgentMessages :exec
DELETE FROM agent_message WHERE conversation_id = ?
`

func (q *Queries) DeleteAgentMessages(ctx context.Context, conversationID string) error {
	_, err := q.db.ExecContext(ctx, deleteAgentMessages, conversationID)
	return err
}

const deleteEmptyAgentConversations = `-- name: DeleteEmptyAgentConversations :execrows
DELETE FROM agent_conversation
WHERE updated_at < ? AND NOT EXISTS (SELECT 1 FROM agent_message m WHERE m.conversation_id = agent_conversation.id)
`

// Rows made by an upload or a request that never got as far as a message.
func (q *Queries) DeleteEmptyAgentConversations(ctx context.Context, updatedAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteEmptyAgentConversations, updatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAgentConversation = `-- name: GetAgentConversation :one
SELECT id, mode, title, device_id, bank_id, lesson_id, question_id, created_at, updated_at FROM agent_conversation WHERE id = ?
`

func (q *Queries) GetAgentConversation(ctx context.Context, id string) (AgentConversation, error) {
	row := q.db.QueryRowContext(ctx, getAgentConversation, id)
	var i AgentConversation
	err := row.Scan(
		&i.ID,
		&i.Mode,
		&i.Title,
		&i.DeviceID,
		&i.BankID,
		&i.LessonID,
		&i.QuestionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAgentMessage = `-- name: InsertAgentMessage :one
INSERT INTO agent_message (conversation_id, role, text, tools, draft_ids, attachment_ids, note, error, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertAgentMessageParams struct {
	ConversationID string `json:"conversation_id"`
	Role           string `json:"role"`
	Text           string `json:"text"`
	Tools          string `json:"tools"`
	DraftIds       string `json:"draft_ids"`
	AttachmentIds  string `json:"attachment_ids"`
	Note           string `json:"note"`
	Error          string `json:"error"`
	CreatedAt      int64  `json:"created_at"`
}

func (q *Queries) InsertAgentMessage(ctx context.Context, arg InsertAgentMessageParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertAgentMessage,
		arg.ConversationID,
		arg.Role,
		arg.Text,
		arg.Tools,
		arg.DraftIds,
		arg.AttachmentIds,
		arg.Note,
		arg.Error,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listAgentConversations = `-- name: ListAgentConversations :many
SELECT c.id, c.mode, c.title, c.bank_id, c.lesson_id, c.question_id, c.updated_at,
       (SELECT COUNT(*) FROM agent_message m WHERE m.conversation_id = c.id) AS message_count,
       (SELECT COUNT(*) FROM agent_draft d JOIN question q ON q.id = d.question_id
         WHERE d.conversation_id = c.id AND q.status = 'draft') AS pending_drafts
FROM agent_conversation c
WHERE c.updated_at < ?1
  AND (?2 IS NULL OR c.mode = ?2)
  AND EXISTS (SELECT 1 FROM agent_message m WHERE m.conversation_id = c.id)
ORDER BY c.updated_at DESC, c.id DESC
LIMIT ?3
`

type ListAgentConversationsParams struct {
	Before    int64       `json:"before"`
	Mode      interface{} `json:"mode"`
	PageLimit int64       `json:"page_limit"`
}

type ListAgentConversationsRow struct {
	ID            string `json:"id"`
	Mode          string `json:"mode"`
	Title         string `json:"title"`
	BankID        string `json:"bank_id"`
	LessonID      string `json:"lesson_id"`
	QuestionID    string `json:"question_id"`
	UpdatedAt     int64  `json:"updated_at"`
	MessageCount  int64  `json:"message_count"`
	PendingDrafts int64  `json:"pending_drafts"`
}

// Newest first. Conversations nobody has said anything in yet are not listed.
func (q *Queries) ListAgentConversations(ctx context.Context, arg ListAgentConversationsParams) ([]ListAgentConversationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAgentConversations, arg.Before, arg.Mode, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentConversationsRow{}
	for rows.Next() {
		var i ListAgentConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Mode,
			&i.Title,
			&i.BankID,
			&i.LessonID,
			&i.QuestionID,
			&i.UpdatedAt,
			&i.MessageCount,
			&i.PendingDrafts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentMessages = `-- name: ListAgentMessages :many
SELECT id, conversation_id, role, text, tools, draft_ids, attachment_ids, note, error, created_at FROM agent_message WHERE conversation_id = ? ORDER BY id
`

func (q *Queries) ListAgentMessages(ctx context.Context, conversationID string) ([]AgentMessage, error) {
	rows, err := q.db.QueryContext(ctx, listAgentMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentMessage{}
	for rows.Next() {
		var i AgentMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Text,
			&i.Tools,
			&i.DraftIds,
			&i.AttachmentIds,
			&i.Note,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationDrafts = `-- name: ListConversationDrafts :many
SELECT q.id, q.bank_id, q.chunk_id, q.type, q.stem, q.options, q.answer, q.explanation, q.difficulty, q.tags, q.source_quote, q.status, q.review_note, q.content_hash, q.gen_model, q.gen_prompt_version, q.flag_count, q.sync_seq, q.created_at, q.updated_at, d.lesson_id AS draft_lesson_id, d.verified
FROM agent_draft d JOIN question q ON q.id = d.question_id
WHERE d.conversation_id = ?
ORDER BY d.created_at, q.id
`

type ListConversationDraftsRow struct {
	ID               string         `json:"id"`
	BankID           string         `json:"bank_id"`
	ChunkID          sql.NullString `json:"chunk_id"`
	Type             string         `json:"type"`
	Stem             string         `json:"stem"`
	Options          string         `json:"options"`
	Answer           string         `json:"answer"`
	Explanation      string         `json:"explanation"`
	Difficulty       int64          `json:"difficulty"`
	Tags             string         `json:"tags"`
	SourceQuote      string         `json:"source_quote"`
	Status           string         `json:"status"`
	ReviewNote       string         `json:"review_note"`
	ContentHash      string         `json:"content_hash"`
	GenModel         string         `json:"gen_model"`
	GenPromptVersion string         `json:"gen_prompt_version"`
	FlagCount        int64          `json:"flag_count"`
	SyncSeq          sql.NullInt64  `json:"sync_seq"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
	DraftLessonID    string         `json:"draft_lesson_id"`
	Verified         int64          `json:"verified"`
}

// Every draft of a conversation whatever became of it, so a reopened chat can show the cards as they stand.
func (q *Queries) ListConversationDrafts(ctx context.Context, conversationID string) ([]ListConversationDraftsRow, error) {
	rows, err := q.db.QueryContext(ctx, listConversationDrafts, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationDraftsRow{}
	for rows.Next() {
		var i ListConversationDraftsRow
		if err := rows.Scan(
			&i.ID,
			&i.BankID,
			&i.ChunkID,
			&i.Type,
			&i.Stem,
			&i.Options,
			&i.Answer,
			&i.Explanation,
			&i.Difficulty,
			&i.Tags,
			&i.SourceQuote,
			&i.Status,
			&i.ReviewNote,
			&i.ContentHash,
			&i.GenModel,
			&i.GenPromptVersion,
			&i.FlagCount,
			&i.SyncSeq,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DraftLessonID,
			&i.Verified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectConversationDrafts = `-- name: RejectConversationDrafts :execrows
UPDATE question SET status = 'rejected', review_note = 'discarded: conversation deleted', updated_at = ?
WHERE status = 'draft' AND id IN (SELECT question_id FROM agent_draft WHERE conversation_id = ?)
`

type RejectConversationDraftsParams struct {
	UpdatedAt      int64  `json:"updated_at"`
	ConversationID string `json:"conversation_id"`
}

// Deleting a conversation throws away the drafts nobody decided on; accepted questions are not touched.
func (q *Queries) RejectConversationDrafts(ctx context.Context, arg RejectConversationDraftsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, rejectConversationDrafts, arg.UpdatedAt, arg.ConversationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setAgentConversationTitle = `-- name: SetAgentConversationTitle :exec
UPDATE agent_conversation SET title = ? WHERE id = ?
`

type SetAgentConversationTitleParams struct {
	Title string `json:"title"`
	ID    string `json:"id"`
}

func (q *Queries) SetAgentConversationTitle(ctx context.Context, arg SetAgentConversationTitleParams) error {
	_, err := q.db.ExecContext(ctx, setAgentConversationTitle, arg.Title, arg.ID)
	return err
}

const touchAgentConversation = `-- name: TouchAgentConversation :exec
UPDATE agent_conversation SET updated_at = ? WHERE id = ?
`

type TouchAgentConversationParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) TouchAgentConversation(ctx context.Context, arg TouchAgentConversationParams) error {
	_, err := q.db.ExecContext(ctx, touchAgentConversation, arg.UpdatedAt, arg.ID)
	return err
}

const upsertAgentConversation = `-- name: UpsertAgentConversation :exec
INSERT INTO agent_conversation (id, mode, device_id, bank_id, lesson_id, question_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET device_id = excluded.device_id, updated_at = excluded.updated_at
`

type UpsertAgentConversationParams struct {
	ID         string `json:"id"`
	Mode       string `json:"mode"`
	DeviceID   string `json:"device_id"`
	BankID     string `json:"bank_id"`
	LessonID   string `json:"lesson_id"`
	QuestionID string `json:"question_id"`
	CreatedAt  int64  `json:"created_at"`
	UpdatedAt  int64  `json:"updated_at"`
}

// Creates the conversation, or marks it as just spoken in (its mode and starting context stay as they were).
func (q *Queries) UpsertAgentConversation(ctx context.Context, arg UpsertAgentConversationParams) error {
	_, err := q.db.ExecContext(ctx, upsertAgentConversation,
		arg.ID,
		arg.Mode,
		arg.DeviceID,
		arg.BankID,
		arg.LessonID,
		arg.QuestionID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
