// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai.sql

package store

import (
	"context"
)

const countAINotesAdmin = `-- name: CountAINotesAdmin :one
SELECT COUNT(*) FROM ai_note n
JOIN question q ON q.id = n.question_id
WHERE (?1 IS NULL OR q.bank_id = ?1)
  AND (?2 IS NULL
       OR instr(q.stem, ?2) > 0 OR instr(n.content, ?2) > 0)
`

type CountAINotesAdminParams struct {
	BankID interface{} `json:"bank_id"`
	Search interface{} `json:"search"`
}

func (q *Queries) CountAINotesAdmin(ctx context.Context, arg CountAINotesAdminParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAINotesAdmin, arg.BankID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSetting = `-- name: GetSetting :one
SELECT value FROM app_setting WHERE key = ?
`

func (q *Queries) GetSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const listAINotesAdmin = `-- name: ListAINotesAdmin :many
SELECT n.question_id, n.content, n.model, n.prompt_version, n.selected, n.updated_at, n.device_id,
       q.bank_id, b.title AS bank_title, q.type, q.stem, q.options, q.answer, q.explanation
FROM ai_note n
JOIN question q ON q.id = n.question_id
JOIN bank b ON b.id = q.bank_id
WHERE (?1 IS NULL OR q.bank_id = ?1)
  AND (?2 IS NULL
       OR instr(q.stem, ?2) > 0 OR instr(n.content, ?2) > 0)
ORDER BY n.updated_at DESC, n.question_id DESC
LIMIT ?4 OFFSET ?3
`

type ListAINotesAdminParams struct {
	BankID     interface{} `json:"bank_id"`
	Search     interface{} `json:"search"`
	PageOffset int64       `json:"page_offset"`
	PageLimit  int64       `json:"page_limit"`
}

type ListAINotesAdminRow struct {
	QuestionID    string `json:"question_id"`
	Content       string `json:"content"`
	Model         string `json:"model"`
	PromptVersion string `json:"prompt_version"`
	Selected      string `json:"selected"`
	UpdatedAt     int64  `json:"updated_at"`
	DeviceID      string `json:"device_id"`
	BankID        string `json:"bank_id"`
	BankTitle     string `json:"bank_title"`
	Type          string `json:"type"`
	Stem          string `json:"stem"`
	Options       string `json:"options"`
	Answer        string `json:"answer"`
	Explanation   string `json:"explanation"`
}

func (q *Queries) ListAINotesAdmin(ctx context.Context, arg ListAINotesAdminParams) ([]ListAINotesAdminRow, error) {
	rows, err := q.db.QueryContext(ctx, listAINotesAdmin,
		arg.BankID,
		arg.Search,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAINotesAdminRow{}
	for rows.Next() {
		var i ListAINotesAdminRow
		if err := rows.Scan(
			&i.QuestionID,
			&i.Content,
			&i.Model,
			&i.PromptVersion,
			&i.Selected,
			&i.UpdatedAt,
			&i.DeviceID,
			&i.BankID,
			&i.BankTitle,
			&i.Type,
			&i.Stem,
			&i.Options,
			&i.Answer,
			&i.Explanation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAINotesSince = `-- name: ListAINotesSince :many
SELECT question_id, content, model, prompt_version, selected, updated_at, device_id, sync_seq FROM ai_note
WHERE sync_seq > ?1
ORDER BY sync_seq ASC
LIMIT ?2
`

type ListAINotesSinceParams struct {
	Since     int64 `json:"since"`
	PageLimit int64 `json:"page_limit"`
}

func (q *Queries) ListAINotesSince(ctx context.Context, arg ListAINotesSinceParams) ([]AiNote, error) {
	rows, err := q.db.QueryContext(ctx, listAINotesSince, arg.Since, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiNote{}
	for rows.Next() {
		var i AiNote
		if err := rows.Scan(
			&i.QuestionID,
			&i.Content,
			&i.Model,
			&i.PromptVersion,
			&i.Selected,
			&i.UpdatedAt,
			&i.DeviceID,
			&i.SyncSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putSetting = `-- name: PutSetting :exec
INSERT INTO app_setting (key, value) VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type PutSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) PutSetting(ctx context.Context, arg PutSettingParams) error {
	_, err := q.db.ExecContext(ctx, putSetting, arg.Key, arg.Value)
	return err
}

const upsertAINote = `-- name: UpsertAINote :execrows
INSERT INTO ai_note (question_id, content, model, prompt_version, selected, updated_at, device_id, sync_seq)
SELECT q.id, ?1, ?2, ?3, ?4,
       ?5, ?6, ?7
FROM question q WHERE q.id = ?8
ON CONFLICT(question_id) DO UPDATE SET
  content = excluded.content, model = excluded.model, prompt_version = excluded.prompt_version,
  selected = excluded.selected, updated_at = excluded.updated_at,
  device_id = excluded.device_id, sync_seq = excluded.sync_seq
WHERE excluded.updated_at > ai_note.updated_at
`

type UpsertAINoteParams struct {
	Content       string `json:"content"`
	Model         string `json:"model"`
	PromptVersion string `json:"prompt_version"`
	Selected      string `json:"selected"`
	UpdatedAt     int64  `json:"updated_at"`
	DeviceID      string `json:"device_id"`
	SyncSeq       int64  `json:"sync_seq"`
	QuestionID    string `json:"question_id"`
}

func (q *Queries) UpsertAINote(ctx context.Context, arg UpsertAINoteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertAINote,
		arg.Content,
		arg.Model,
		arg.PromptVersion,
		arg.Selected,
		arg.UpdatedAt,
		arg.DeviceID,
		arg.SyncSeq,
		arg.QuestionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
