// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bank.sql

package store

import (
	"context"
)

const countPublishedQuestionsByBank = `-- name: CountPublishedQuestionsByBank :one
SELECT COUNT(*) FROM question WHERE bank_id = ? AND status = 'published'
`

func (q *Queries) CountPublishedQuestionsByBank(ctx context.Context, bankID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPublishedQuestionsByBank, bankID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBank = `-- name: CreateBank :one
INSERT INTO bank (id, title, description, created_at)
VALUES (?, ?, ?, ?)
RETURNING id, title, description, created_at
`

type CreateBankParams struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	CreatedAt   int64  `json:"created_at"`
}

func (q *Queries) CreateBank(ctx context.Context, arg CreateBankParams) (Bank, error) {
	row := q.db.QueryRowContext(ctx, createBank,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.CreatedAt,
	)
	var i Bank
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getBank = `-- name: GetBank :one
SELECT id, title, description, created_at FROM bank WHERE id = ?
`

func (q *Queries) GetBank(ctx context.Context, id string) (Bank, error) {
	row := q.db.QueryRowContext(ctx, getBank, id)
	var i Bank
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listBanks = `-- name: ListBanks :many
SELECT id, title, description, created_at FROM bank ORDER BY created_at DESC
`

func (q *Queries) ListBanks(ctx context.Context) ([]Bank, error) {
	rows, err := q.db.QueryContext(ctx, listBanks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bank{}
	for rows.Next() {
		var i Bank
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
