// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chunk.sql

package store

import (
	"context"
	"database/sql"
)

const getChunk = `-- name: GetChunk :one
SELECT id, document_id, seq, heading_path, text, content_hash, status, generated_at FROM chunk WHERE id = ?
`

func (q *Queries) GetChunk(ctx context.Context, id string) (Chunk, error) {
	row := q.db.QueryRowContext(ctx, getChunk, id)
	var i Chunk
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Seq,
		&i.HeadingPath,
		&i.Text,
		&i.ContentHash,
		&i.Status,
		&i.GeneratedAt,
	)
	return i, err
}

const insertChunk = `-- name: InsertChunk :exec
INSERT INTO chunk (id, document_id, seq, heading_path, text, content_hash, status)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertChunkParams struct {
	ID          string `json:"id"`
	DocumentID  string `json:"document_id"`
	Seq         int64  `json:"seq"`
	HeadingPath string `json:"heading_path"`
	Text        string `json:"text"`
	ContentHash string `json:"content_hash"`
	Status      string `json:"status"`
}

func (q *Queries) InsertChunk(ctx context.Context, arg InsertChunkParams) error {
	_, err := q.db.ExecContext(ctx, insertChunk,
		arg.ID,
		arg.DocumentID,
		arg.Seq,
		arg.HeadingPath,
		arg.Text,
		arg.ContentHash,
		arg.Status,
	)
	return err
}

const listChunksByDocument = `-- name: ListChunksByDocument :many
SELECT id, document_id, seq, heading_path, text, content_hash, status, generated_at FROM chunk WHERE document_id = ? ORDER BY seq
`

func (q *Queries) ListChunksByDocument(ctx context.Context, documentID string) ([]Chunk, error) {
	rows, err := q.db.QueryContext(ctx, listChunksByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Chunk{}
	for rows.Next() {
		var i Chunk
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Seq,
			&i.HeadingPath,
			&i.Text,
			&i.ContentHash,
			&i.Status,
			&i.GeneratedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChunksToGenerate = `-- name: ListChunksToGenerate :many
SELECT id, document_id, seq, heading_path, text, content_hash, status, generated_at FROM chunk
WHERE document_id = ? AND status = 'active' AND generated_at IS NULL
ORDER BY seq
`

func (q *Queries) ListChunksToGenerate(ctx context.Context, documentID string) ([]Chunk, error) {
	rows, err := q.db.QueryContext(ctx, listChunksToGenerate, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Chunk{}
	for rows.Next() {
		var i Chunk
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Seq,
			&i.HeadingPath,
			&i.Text,
			&i.ContentHash,
			&i.Status,
			&i.GeneratedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markChunkGenerated = `-- name: MarkChunkGenerated :execrows
UPDATE chunk SET generated_at = ? WHERE id = ? AND generated_at IS NULL
`

type MarkChunkGeneratedParams struct {
	GeneratedAt sql.NullInt64 `json:"generated_at"`
	ID          string        `json:"id"`
}

func (q *Queries) MarkChunkGenerated(ctx context.Context, arg MarkChunkGeneratedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markChunkGenerated, arg.GeneratedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateChunk = `-- name: UpdateChunk :exec
UPDATE chunk SET seq = ?, heading_path = ?, status = ? WHERE id = ?
`

type UpdateChunkParams struct {
	Seq         int64  `json:"seq"`
	HeadingPath string `json:"heading_path"`
	Status      string `json:"status"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateChunk(ctx context.Context, arg UpdateChunkParams) error {
	_, err := q.db.ExecContext(ctx, updateChunk,
		arg.Seq,
		arg.HeadingPath,
		arg.Status,
		arg.ID,
	)
	return err
}
