// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document.sql

package store

import (
	"context"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO document (id, bank_id, title, source_path, content, content_hash, status, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, bank_id, title, source_path, content, content_hash, status, created_at, updated_at
`

type CreateDocumentParams struct {
	ID          string `json:"id"`
	BankID      string `json:"bank_id"`
	Title       string `json:"title"`
	SourcePath  string `json:"source_path"`
	Content     string `json:"content"`
	ContentHash string `json:"content_hash"`
	Status      string `json:"status"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, createDocument,
		arg.ID,
		arg.BankID,
		arg.Title,
		arg.SourcePath,
		arg.Content,
		arg.ContentHash,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.BankID,
		&i.Title,
		&i.SourcePath,
		&i.Content,
		&i.ContentHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const documentQuestionCounts = `-- name: DocumentQuestionCounts :many
SELECT c.document_id AS document_id, q.status AS status, COUNT(*) AS n
FROM question q
JOIN chunk c ON c.id = q.chunk_id
GROUP BY c.document_id, q.status
`

type DocumentQuestionCountsRow struct {
	DocumentID string `json:"document_id"`
	Status     string `json:"status"`
	N          int64  `json:"n"`
}

func (q *Queries) DocumentQuestionCounts(ctx context.Context) ([]DocumentQuestionCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, documentQuestionCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DocumentQuestionCountsRow{}
	for rows.Next() {
		var i DocumentQuestionCountsRow
		if err := rows.Scan(&i.DocumentID, &i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocument = `-- name: GetDocument :one
SELECT id, bank_id, title, source_path, content, content_hash, status, created_at, updated_at FROM document WHERE id = ?
`

func (q *Queries) GetDocument(ctx context.Context, id string) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.BankID,
		&i.Title,
		&i.SourcePath,
		&i.Content,
		&i.ContentHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentBySourcePath = `-- name: GetDocumentBySourcePath :one
SELECT id, bank_id, title, source_path, content, content_hash, status, created_at, updated_at FROM document WHERE bank_id = ? AND source_path = ?
`

type GetDocumentBySourcePathParams struct {
	BankID     string `json:"bank_id"`
	SourcePath string `json:"source_path"`
}

func (q *Queries) GetDocumentBySourcePath(ctx context.Context, arg GetDocumentBySourcePathParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocumentBySourcePath, arg.BankID, arg.SourcePath)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.BankID,
		&i.Title,
		&i.SourcePath,
		&i.Content,
		&i.ContentHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, bank_id, title, source_path, content, content_hash, status, created_at, updated_at FROM document ORDER BY updated_at DESC
`

func (q *Queries) ListDocuments(ctx context.Context) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.BankID,
			&i.Title,
			&i.SourcePath,
			&i.Content,
			&i.ContentHash,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDocumentStatus = `-- name: SetDocumentStatus :exec
UPDATE document SET status = ?, updated_at = ? WHERE id = ?
`

type SetDocumentStatusParams struct {
	Status    string `json:"status"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) SetDocumentStatus(ctx context.Context, arg SetDocumentStatusParams) error {
	_, err := q.db.ExecContext(ctx, setDocumentStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}

const setDocumentTitle = `-- name: SetDocumentTitle :exec
UPDATE document SET title = ?, updated_at = ? WHERE id = ?
`

type SetDocumentTitleParams struct {
	Title     string `json:"title"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) SetDocumentTitle(ctx context.Context, arg SetDocumentTitleParams) error {
	_, err := q.db.ExecContext(ctx, setDocumentTitle, arg.Title, arg.UpdatedAt, arg.ID)
	return err
}

const updateDocumentContent = `-- name: UpdateDocumentContent :exec
UPDATE document
SET title = ?, content = ?, content_hash = ?, status = ?, updated_at = ?
WHERE id = ?
`

type UpdateDocumentContentParams struct {
	Title       string `json:"title"`
	Content     string `json:"content"`
	ContentHash string `json:"content_hash"`
	Status      string `json:"status"`
	UpdatedAt   int64  `json:"updated_at"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateDocumentContent(ctx context.Context, arg UpdateDocumentContentParams) error {
	_, err := q.db.ExecContext(ctx, updateDocumentContent,
		arg.Title,
		arg.Content,
		arg.ContentHash,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
