// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: flag.sql

package store

import (
	"context"
	"database/sql"
)

const clearQuestionFlagCount = `-- name: ClearQuestionFlagCount :exec
UPDATE question SET flag_count = 0 WHERE id = ?
`

func (q *Queries) ClearQuestionFlagCount(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, clearQuestionFlagCount, id)
	return err
}

const countFlaggedQuestions = `-- name: CountFlaggedQuestions :one
SELECT COUNT(*) FROM question
WHERE flag_count > 0 AND (?1 IS NULL OR bank_id = ?1)
`

func (q *Queries) CountFlaggedQuestions(ctx context.Context, bankID interface{}) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFlaggedQuestions, bankID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertQuestionFlag = `-- name: InsertQuestionFlag :exec
INSERT INTO question_flag (id, question_id, reason, created_at)
VALUES (?, ?, ?, ?)
`

type InsertQuestionFlagParams struct {
	ID         string `json:"id"`
	QuestionID string `json:"question_id"`
	Reason     string `json:"reason"`
	CreatedAt  int64  `json:"created_at"`
}

func (q *Queries) InsertQuestionFlag(ctx context.Context, arg InsertQuestionFlagParams) error {
	_, err := q.db.ExecContext(ctx, insertQuestionFlag,
		arg.ID,
		arg.QuestionID,
		arg.Reason,
		arg.CreatedAt,
	)
	return err
}

const listQuestionFlags = `-- name: ListQuestionFlags :many
SELECT id, question_id, reason, created_at, resolved_at FROM question_flag
WHERE question_id = ?
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListQuestionFlags(ctx context.Context, questionID string) ([]QuestionFlag, error) {
	rows, err := q.db.QueryContext(ctx, listQuestionFlags, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuestionFlag{}
	for rows.Next() {
		var i QuestionFlag
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Reason,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveQuestionFlags = `-- name: ResolveQuestionFlags :exec
UPDATE question_flag SET resolved_at = ?
WHERE question_id = ? AND resolved_at IS NULL
`

type ResolveQuestionFlagsParams struct {
	ResolvedAt sql.NullInt64 `json:"resolved_at"`
	QuestionID string        `json:"question_id"`
}

func (q *Queries) ResolveQuestionFlags(ctx context.Context, arg ResolveQuestionFlagsParams) error {
	_, err := q.db.ExecContext(ctx, resolveQuestionFlags, arg.ResolvedAt, arg.QuestionID)
	return err
}
