// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: job.sql

package store

import (
	"context"
	"database/sql"
)

const claimJob = `-- name: ClaimJob :one
UPDATE job
SET status = 'running', attempts = attempts + 1, lease_until = ?1, updated_at = ?2
WHERE id = (
  SELECT j.id FROM job j
  WHERE j.status = 'pending' AND j.run_at <= ?2
  ORDER BY j.run_at, j.created_at
  LIMIT 1
)
RETURNING id, type, document_id, payload, status, attempts, max_attempts, run_at, lease_until, last_error, created_at, updated_at
`

type ClaimJobParams struct {
	LeaseUntil sql.NullInt64 `json:"lease_until"`
	Now        int64         `json:"now"`
}

func (q *Queries) ClaimJob(ctx context.Context, arg ClaimJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, claimJob, arg.LeaseUntil, arg.Now)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.DocumentID,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.RunAt,
		&i.LeaseUntil,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeJob = `-- name: CompleteJob :exec
UPDATE job SET status = 'done', lease_until = NULL, last_error = '', updated_at = ? WHERE id = ?
`

type CompleteJobParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) error {
	_, err := q.db.ExecContext(ctx, completeJob, arg.UpdatedAt, arg.ID)
	return err
}

const countActiveJobsByDocument = `-- name: CountActiveJobsByDocument :one
SELECT COUNT(*) FROM job WHERE document_id = ? AND status IN ('pending','running')
`

func (q *Queries) CountActiveJobsByDocument(ctx context.Context, documentID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveJobsByDocument, documentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countJobsByDocumentAndStatus = `-- name: CountJobsByDocumentAndStatus :one
SELECT COUNT(*) FROM job WHERE document_id = ? AND status = ?
`

type CountJobsByDocumentAndStatusParams struct {
	DocumentID string `json:"document_id"`
	Status     string `json:"status"`
}

func (q *Queries) CountJobsByDocumentAndStatus(ctx context.Context, arg CountJobsByDocumentAndStatusParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countJobsByDocumentAndStatus, arg.DocumentID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deferJob = `-- name: DeferJob :exec
UPDATE job
SET status = 'pending', attempts = MAX(attempts - 1, 0), run_at = ?, lease_until = NULL,
    last_error = ?, updated_at = ?
WHERE id = ?
`

type DeferJobParams struct {
	RunAt     int64  `json:"run_at"`
	LastError string `json:"last_error"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

// Put a running job back without charging an attempt (e.g. daily budget spent).
func (q *Queries) DeferJob(ctx context.Context, arg DeferJobParams) error {
	_, err := q.db.ExecContext(ctx, deferJob,
		arg.RunAt,
		arg.LastError,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const failJob = `-- name: FailJob :exec
UPDATE job SET status = 'failed', lease_until = NULL, last_error = ?, updated_at = ? WHERE id = ?
`

type FailJobParams struct {
	LastError string `json:"last_error"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) error {
	_, err := q.db.ExecContext(ctx, failJob, arg.LastError, arg.UpdatedAt, arg.ID)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, type, document_id, payload, status, attempts, max_attempts, run_at, lease_until, last_error, created_at, updated_at FROM job WHERE id = ?
`

func (q *Queries) GetJob(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.DocumentID,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.RunAt,
		&i.LeaseUntil,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertJob = `-- name: InsertJob :exec
INSERT INTO job (id, type, document_id, payload, status, attempts, max_attempts, run_at, last_error, created_at, updated_at)
VALUES (?, ?, ?, ?, 'pending', 0, ?, ?, '', ?, ?)
`

type InsertJobParams struct {
	ID          string `json:"id"`
	Type        string `json:"type"`
	DocumentID  string `json:"document_id"`
	Payload     string `json:"payload"`
	MaxAttempts int64  `json:"max_attempts"`
	RunAt       int64  `json:"run_at"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) error {
	_, err := q.db.ExecContext(ctx, insertJob,
		arg.ID,
		arg.Type,
		arg.DocumentID,
		arg.Payload,
		arg.MaxAttempts,
		arg.RunAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listJobs = `-- name: ListJobs :many
SELECT id, type, document_id, payload, status, attempts, max_attempts, run_at, lease_until, last_error, created_at, updated_at FROM job
WHERE (?1 IS NULL OR status = ?1)
  AND (?2 IS NULL OR document_id = ?2)
ORDER BY created_at DESC, id DESC
LIMIT ?3
`

type ListJobsParams struct {
	Status     interface{} `json:"status"`
	DocumentID interface{} `json:"document_id"`
	PageLimit  int64       `json:"page_limit"`
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobs, arg.Status, arg.DocumentID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.DocumentID,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.RunAt,
			&i.LeaseUntil,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recoverExpiredJobs = `-- name: RecoverExpiredJobs :execrows
UPDATE job
SET status = 'pending', lease_until = NULL, updated_at = ?1
WHERE status = 'running' AND lease_until IS NOT NULL AND lease_until < ?1
`

func (q *Queries) RecoverExpiredJobs(ctx context.Context, now int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, recoverExpiredJobs, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const rescheduleJob = `-- name: RescheduleJob :exec
UPDATE job SET status = 'pending', run_at = ?, lease_until = NULL, last_error = ?, updated_at = ? WHERE id = ?
`

type RescheduleJobParams struct {
	RunAt     int64  `json:"run_at"`
	LastError string `json:"last_error"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) RescheduleJob(ctx context.Context, arg RescheduleJobParams) error {
	_, err := q.db.ExecContext(ctx, rescheduleJob,
		arg.RunAt,
		arg.LastError,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const retryFailedJob = `-- name: RetryFailedJob :execrows
UPDATE job
SET status = 'pending', attempts = 0, run_at = ?1, last_error = '', updated_at = ?1
WHERE id = ?2 AND status = 'failed'
`

type RetryFailedJobParams struct {
	Now int64  `json:"now"`
	ID  string `json:"id"`
}

func (q *Queries) RetryFailedJob(ctx context.Context, arg RetryFailedJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, retryFailedJob, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const retryFailedJobsByDocument = `-- name: RetryFailedJobsByDocument :execrows
UPDATE job
SET status = 'pending', attempts = 0, run_at = ?1, last_error = '', updated_at = ?1
WHERE document_id = ?2 AND status = 'failed'
`

type RetryFailedJobsByDocumentParams struct {
	Now        int64  `json:"now"`
	DocumentID string `json:"document_id"`
}

func (q *Queries) RetryFailedJobsByDocument(ctx context.Context, arg RetryFailedJobsByDocumentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, retryFailedJobsByDocument, arg.Now, arg.DocumentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const supersedeFailedJobs = `-- name: SupersedeFailedJobs :exec
UPDATE job
SET status = 'done', last_error = 'superseded by re-import', updated_at = ?
WHERE document_id = ? AND status = 'failed'
`

type SupersedeFailedJobsParams struct {
	UpdatedAt  int64  `json:"updated_at"`
	DocumentID string `json:"document_id"`
}

// A re-import regenerates whatever work is still needed, so old failures no
// longer describe the document's state.
func (q *Queries) SupersedeFailedJobs(ctx context.Context, arg SupersedeFailedJobsParams) error {
	_, err := q.db.ExecContext(ctx, supersedeFailedJobs, arg.UpdatedAt, arg.DocumentID)
	return err
}
