// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lesson.sql

package store

import (
	"context"
)

const listLessons = `-- name: ListLessons :many
SELECT c.id, c.seq, c.heading_path, c.text, c.content_hash,
       d.id AS document_id, d.bank_id, d.title AS document_title, d.created_at AS document_created_at
FROM chunk c JOIN document d ON d.id = c.document_id
WHERE c.status = 'active'
ORDER BY d.bank_id, d.created_at, d.id, c.seq
`

type ListLessonsRow struct {
	ID                string `json:"id"`
	Seq               int64  `json:"seq"`
	HeadingPath       string `json:"heading_path"`
	Text              string `json:"text"`
	ContentHash       string `json:"content_hash"`
	DocumentID        string `json:"document_id"`
	BankID            string `json:"bank_id"`
	DocumentTitle     string `json:"document_title"`
	DocumentCreatedAt int64  `json:"document_created_at"`
}

// Every readable section of every document (a chapter of a bank), in reading order: documents
// in the order they were added, sections in document order. Superseded sections are left out.
func (q *Queries) ListLessons(ctx context.Context) ([]ListLessonsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLessons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLessonsRow{}
	for rows.Next() {
		var i ListLessonsRow
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.HeadingPath,
			&i.Text,
			&i.ContentHash,
			&i.DocumentID,
			&i.BankID,
			&i.DocumentTitle,
			&i.DocumentCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
