// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: llm.sql

package store

import (
	"context"
)

const insertLLMCall = `-- name: InsertLLMCall :exec
INSERT INTO llm_call_log (
  id, job_id, role, provider, model, input_tokens, output_tokens, cached_tokens,
  latency_ms, ok, error, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertLLMCallParams struct {
	ID           string `json:"id"`
	JobID        string `json:"job_id"`
	Role         string `json:"role"`
	Provider     string `json:"provider"`
	Model        string `json:"model"`
	InputTokens  int64  `json:"input_tokens"`
	OutputTokens int64  `json:"output_tokens"`
	CachedTokens int64  `json:"cached_tokens"`
	LatencyMs    int64  `json:"latency_ms"`
	Ok           int64  `json:"ok"`
	Error        string `json:"error"`
	CreatedAt    int64  `json:"created_at"`
}

func (q *Queries) InsertLLMCall(ctx context.Context, arg InsertLLMCallParams) error {
	_, err := q.db.ExecContext(ctx, insertLLMCall,
		arg.ID,
		arg.JobID,
		arg.Role,
		arg.Provider,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CachedTokens,
		arg.LatencyMs,
		arg.Ok,
		arg.Error,
		arg.CreatedAt,
	)
	return err
}

const sumTokensSince = `-- name: SumTokensSince :one
SELECT CAST(COALESCE(SUM(input_tokens + output_tokens), 0) AS INTEGER) AS total
FROM llm_call_log WHERE created_at >= ?
`

func (q *Queries) SumTokensSince(ctx context.Context, createdAt int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumTokensSince, createdAt)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const usageByDay = `-- name: UsageByDay :many
SELECT date(created_at / 1000, 'unixepoch') AS day,
       model,
       COUNT(*)                                              AS calls,
       CAST(COALESCE(SUM(input_tokens), 0) AS INTEGER)       AS input_tokens,
       CAST(COALESCE(SUM(output_tokens), 0) AS INTEGER)      AS output_tokens,
       CAST(COALESCE(SUM(cached_tokens), 0) AS INTEGER)      AS cached_tokens,
       CAST(COALESCE(SUM(1 - ok), 0) AS INTEGER)             AS failures
FROM llm_call_log
WHERE created_at >= ?
GROUP BY day, model
ORDER BY day DESC, model
`

type UsageByDayRow struct {
	Day          interface{} `json:"day"`
	Model        string      `json:"model"`
	Calls        int64       `json:"calls"`
	InputTokens  int64       `json:"input_tokens"`
	OutputTokens int64       `json:"output_tokens"`
	CachedTokens int64       `json:"cached_tokens"`
	Failures     int64       `json:"failures"`
}

func (q *Queries) UsageByDay(ctx context.Context, createdAt int64) ([]UsageByDayRow, error) {
	rows, err := q.db.QueryContext(ctx, usageByDay, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageByDayRow{}
	for rows.Next() {
		var i UsageByDayRow
		if err := rows.Scan(
			&i.Day,
			&i.Model,
			&i.Calls,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CachedTokens,
			&i.Failures,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
