// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: llm_config.sql

package store

import (
	"context"
)

const deleteLLMModel = `-- name: DeleteLLMModel :exec
DELETE FROM llm_model WHERE id = ?
`

func (q *Queries) DeleteLLMModel(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteLLMModel, id)
	return err
}

const deleteLLMProvider = `-- name: DeleteLLMProvider :exec
DELETE FROM llm_provider WHERE id = ?
`

func (q *Queries) DeleteLLMProvider(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteLLMProvider, id)
	return err
}

const getLLMModel = `-- name: GetLLMModel :one
SELECT id, provider_id, name, model, max_tokens, temperature, effort, created_at, updated_at FROM llm_model WHERE id = ?
`

func (q *Queries) GetLLMModel(ctx context.Context, id string) (LlmModel, error) {
	row := q.db.QueryRowContext(ctx, getLLMModel, id)
	var i LlmModel
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Name,
		&i.Model,
		&i.MaxTokens,
		&i.Temperature,
		&i.Effort,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLLMProvider = `-- name: GetLLMProvider :one
SELECT id, name, protocol, base_url, api_key, created_at, updated_at FROM llm_provider WHERE id = ?
`

func (q *Queries) GetLLMProvider(ctx context.Context, id string) (LlmProvider, error) {
	row := q.db.QueryRowContext(ctx, getLLMProvider, id)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Protocol,
		&i.BaseUrl,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertLLMModel = `-- name: InsertLLMModel :exec
INSERT INTO llm_model (id, provider_id, name, model, max_tokens, temperature, effort, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertLLMModelParams struct {
	ID          string  `json:"id"`
	ProviderID  string  `json:"provider_id"`
	Name        string  `json:"name"`
	Model       string  `json:"model"`
	MaxTokens   int64   `json:"max_tokens"`
	Temperature float64 `json:"temperature"`
	Effort      string  `json:"effort"`
	CreatedAt   int64   `json:"created_at"`
	UpdatedAt   int64   `json:"updated_at"`
}

func (q *Queries) InsertLLMModel(ctx context.Context, arg InsertLLMModelParams) error {
	_, err := q.db.ExecContext(ctx, insertLLMModel,
		arg.ID,
		arg.ProviderID,
		arg.Name,
		arg.Model,
		arg.MaxTokens,
		arg.Temperature,
		arg.Effort,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertLLMProvider = `-- name: InsertLLMProvider :exec
INSERT INTO llm_provider (id, name, protocol, base_url, api_key, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertLLMProviderParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Protocol  string `json:"protocol"`
	BaseUrl   string `json:"base_url"`
	ApiKey    string `json:"api_key"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) InsertLLMProvider(ctx context.Context, arg InsertLLMProviderParams) error {
	_, err := q.db.ExecContext(ctx, insertLLMProvider,
		arg.ID,
		arg.Name,
		arg.Protocol,
		arg.BaseUrl,
		arg.ApiKey,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listLLMModels = `-- name: ListLLMModels :many
SELECT id, provider_id, name, model, max_tokens, temperature, effort, created_at, updated_at FROM llm_model ORDER BY created_at, id
`

func (q *Queries) ListLLMModels(ctx context.Context) ([]LlmModel, error) {
	rows, err := q.db.QueryContext(ctx, listLLMModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LlmModel{}
	for rows.Next() {
		var i LlmModel
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Name,
			&i.Model,
			&i.MaxTokens,
			&i.Temperature,
			&i.Effort,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLLMModelsByProvider = `-- name: ListLLMModelsByProvider :many
SELECT id, provider_id, name, model, max_tokens, temperature, effort, created_at, updated_at FROM llm_model WHERE provider_id = ? ORDER BY created_at, id
`

func (q *Queries) ListLLMModelsByProvider(ctx context.Context, providerID string) ([]LlmModel, error) {
	rows, err := q.db.QueryContext(ctx, listLLMModelsByProvider, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LlmModel{}
	for rows.Next() {
		var i LlmModel
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Name,
			&i.Model,
			&i.MaxTokens,
			&i.Temperature,
			&i.Effort,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLLMProviders = `-- name: ListLLMProviders :many
SELECT id, name, protocol, base_url, api_key, created_at, updated_at FROM llm_provider ORDER BY created_at, id
`

func (q *Queries) ListLLMProviders(ctx context.Context) ([]LlmProvider, error) {
	rows, err := q.db.QueryContext(ctx, listLLMProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LlmProvider{}
	for rows.Next() {
		var i LlmProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Protocol,
			&i.BaseUrl,
			&i.ApiKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLLMModel = `-- name: UpdateLLMModel :execrows
UPDATE llm_model SET provider_id = ?, name = ?, model = ?, max_tokens = ?, temperature = ?, effort = ?, updated_at = ?
WHERE id = ?
`

type UpdateLLMModelParams struct {
	ProviderID  string  `json:"provider_id"`
	Name        string  `json:"name"`
	Model       string  `json:"model"`
	MaxTokens   int64   `json:"max_tokens"`
	Temperature float64 `json:"temperature"`
	Effort      string  `json:"effort"`
	UpdatedAt   int64   `json:"updated_at"`
	ID          string  `json:"id"`
}

func (q *Queries) UpdateLLMModel(ctx context.Context, arg UpdateLLMModelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateLLMModel,
		arg.ProviderID,
		arg.Name,
		arg.Model,
		arg.MaxTokens,
		arg.Temperature,
		arg.Effort,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateLLMProvider = `-- name: UpdateLLMProvider :execrows
UPDATE llm_provider SET name = ?, protocol = ?, base_url = ?, api_key = ?, updated_at = ? WHERE id = ?
`

type UpdateLLMProviderParams struct {
	Name      string `json:"name"`
	Protocol  string `json:"protocol"`
	BaseUrl   string `json:"base_url"`
	ApiKey    string `json:"api_key"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateLLMProvider(ctx context.Context, arg UpdateLLMProviderParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateLLMProvider,
		arg.Name,
		arg.Protocol,
		arg.BaseUrl,
		arg.ApiKey,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
