// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package store

import (
	"context"
	"strings"
)

const getMedia = `-- name: GetMedia :one
SELECT id, mime, size, width, height, data, created_at FROM media WHERE id = ?
`

func (q *Queries) GetMedia(ctx context.Context, id string) (Medium, error) {
	row := q.db.QueryRowContext(ctx, getMedia, id)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.Mime,
		&i.Size,
		&i.Width,
		&i.Height,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const getMediaMeta = `-- name: GetMediaMeta :one
SELECT id, mime, size, width, height, created_at FROM media WHERE id = ?
`

type GetMediaMetaRow struct {
	ID        string `json:"id"`
	Mime      string `json:"mime"`
	Size      int64  `json:"size"`
	Width     int64  `json:"width"`
	Height    int64  `json:"height"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) GetMediaMeta(ctx context.Context, id string) (GetMediaMetaRow, error) {
	row := q.db.QueryRowContext(ctx, getMediaMeta, id)
	var i GetMediaMetaRow
	err := row.Scan(
		&i.ID,
		&i.Mime,
		&i.Size,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
	)
	return i, err
}

const insertMedia = `-- name: InsertMedia :exec
INSERT INTO media (id, mime, size, width, height, data, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO NOTHING
`

type InsertMediaParams struct {
	ID        string `json:"id"`
	Mime      string `json:"mime"`
	Size      int64  `json:"size"`
	Width     int64  `json:"width"`
	Height    int64  `json:"height"`
	Data      []byte `json:"data"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) InsertMedia(ctx context.Context, arg InsertMediaParams) error {
	_, err := q.db.ExecContext(ctx, insertMedia,
		arg.ID,
		arg.Mime,
		arg.Size,
		arg.Width,
		arg.Height,
		arg.Data,
		arg.CreatedAt,
	)
	return err
}

const listMediaIDs = `-- name: ListMediaIDs :many
SELECT id FROM media WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) ListMediaIDs(ctx context.Context, ids []string) ([]string, error) {
	query := listMediaIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
