// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
)

type AgentAttachment struct {
	ID             string        `json:"id"`
	ConversationID string        `json:"conversation_id"`
	Kind           string        `json:"kind"`
	Name           string        `json:"name"`
	Mime           string        `json:"mime"`
	Size           int64         `json:"size"`
	Chars          int64         `json:"chars"`
	Width          int64         `json:"width"`
	Height         int64         `json:"height"`
	Text           string        `json:"text"`
	Data           []byte        `json:"data"`
	MessageID      sql.NullInt64 `json:"message_id"`
	CreatedAt      int64         `json:"created_at"`
}

type AgentConversation struct {
	ID         string `json:"id"`
	Mode       string `json:"mode"`
	Title      string `json:"title"`
	DeviceID   string `json:"device_id"`
	BankID     string `json:"bank_id"`
	LessonID   string `json:"lesson_id"`
	QuestionID string `json:"question_id"`
	CreatedAt  int64  `json:"created_at"`
	UpdatedAt  int64  `json:"updated_at"`
}

type AgentDraft struct {
	QuestionID     string `json:"question_id"`
	ConversationID string `json:"conversation_id"`
	LessonID       string `json:"lesson_id"`
	DeviceID       string `json:"device_id"`
	Verified       int64  `json:"verified"`
	CreatedAt      int64  `json:"created_at"`
}

type AgentMessage struct {
	ID             int64  `json:"id"`
	ConversationID string `json:"conversation_id"`
	Role           string `json:"role"`
	Text           string `json:"text"`
	Tools          string `json:"tools"`
	DraftIds       string `json:"draft_ids"`
	AttachmentIds  string `json:"attachment_ids"`
	Note           string `json:"note"`
	Error          string `json:"error"`
	CreatedAt      int64  `json:"created_at"`
}

type AiNote struct {
	QuestionID    string `json:"question_id"`
	Content       string `json:"content"`
	Model         string `json:"model"`
	PromptVersion string `json:"prompt_version"`
	Selected      string `json:"selected"`
	UpdatedAt     int64  `json:"updated_at"`
	DeviceID      string `json:"device_id"`
	SyncSeq       int64  `json:"sync_seq"`
}

type AppSetting struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Attempt struct {
	ID         string        `json:"id"`
	QuestionID string        `json:"question_id"`
	DeviceID   string        `json:"device_id"`
	Answer     string        `json:"answer"`
	IsCorrect  int64         `json:"is_correct"`
	DurationMs sql.NullInt64 `json:"duration_ms"`
	AnsweredAt int64         `json:"answered_at"`
	ReceivedAt int64         `json:"received_at"`
	SyncSeq    int64         `json:"sync_seq"`
	ReviewMs   sql.NullInt64 `json:"review_ms"`
}

type Bank struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	CreatedAt   int64  `json:"created_at"`
}

type Chunk struct {
	ID          string        `json:"id"`
	DocumentID  string        `json:"document_id"`
	Seq         int64         `json:"seq"`
	HeadingPath string        `json:"heading_path"`
	Text        string        `json:"text"`
	ContentHash string        `json:"content_hash"`
	Status      string        `json:"status"`
	GeneratedAt sql.NullInt64 `json:"generated_at"`
}

type Document struct {
	ID          string `json:"id"`
	BankID      string `json:"bank_id"`
	Title       string `json:"title"`
	SourcePath  string `json:"source_path"`
	Content     string `json:"content"`
	ContentHash string `json:"content_hash"`
	Status      string `json:"status"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

type Exam struct {
	ID         string        `json:"id"`
	BankID     string        `json:"bank_id"`
	Title      string        `json:"title"`
	FinishedAt int64         `json:"finished_at"`
	Total      int64         `json:"total"`
	Correct    int64         `json:"correct"`
	Answered   int64         `json:"answered"`
	Percent    int64         `json:"percent"`
	Passed     int64         `json:"passed"`
	LimitSec   sql.NullInt64 `json:"limit_sec"`
	UsedMs     int64         `json:"used_ms"`
	DeviceID   string        `json:"device_id"`
	Items      string        `json:"items"`
	SyncSeq    int64         `json:"sync_seq"`
}

type Job struct {
	ID          string        `json:"id"`
	Type        string        `json:"type"`
	DocumentID  string        `json:"document_id"`
	Payload     string        `json:"payload"`
	Status      string        `json:"status"`
	Attempts    int64         `json:"attempts"`
	MaxAttempts int64         `json:"max_attempts"`
	RunAt       int64         `json:"run_at"`
	LeaseUntil  sql.NullInt64 `json:"lease_until"`
	LastError   string        `json:"last_error"`
	CreatedAt   int64         `json:"created_at"`
	UpdatedAt   int64         `json:"updated_at"`
}

type LlmCallLog struct {
	ID           string `json:"id"`
	JobID        string `json:"job_id"`
	Role         string `json:"role"`
	Provider     string `json:"provider"`
	Model        string `json:"model"`
	InputTokens  int64  `json:"input_tokens"`
	OutputTokens int64  `json:"output_tokens"`
	CachedTokens int64  `json:"cached_tokens"`
	LatencyMs    int64  `json:"latency_ms"`
	Ok           int64  `json:"ok"`
	Error        string `json:"error"`
	CreatedAt    int64  `json:"created_at"`
	Source       string `json:"source"`
	DeviceID     string `json:"device_id"`
	RefID        string `json:"ref_id"`
	Estimated    int64  `json:"estimated"`
}

type LlmModel struct {
	ID          string  `json:"id"`
	ProviderID  string  `json:"provider_id"`
	Name        string  `json:"name"`
	Model       string  `json:"model"`
	MaxTokens   int64   `json:"max_tokens"`
	Temperature float64 `json:"temperature"`
	Effort      string  `json:"effort"`
	CreatedAt   int64   `json:"created_at"`
	UpdatedAt   int64   `json:"updated_at"`
	Vision      int64   `json:"vision"`
}

type LlmProvider struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Protocol  string `json:"protocol"`
	BaseUrl   string `json:"base_url"`
	ApiKey    string `json:"api_key"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type Medium struct {
	ID        string `json:"id"`
	Mime      string `json:"mime"`
	Size      int64  `json:"size"`
	Width     int64  `json:"width"`
	Height    int64  `json:"height"`
	Data      []byte `json:"data"`
	CreatedAt int64  `json:"created_at"`
}

type Question struct {
	ID               string         `json:"id"`
	BankID           string         `json:"bank_id"`
	ChunkID          sql.NullString `json:"chunk_id"`
	Type             string         `json:"type"`
	Stem             string         `json:"stem"`
	Options          string         `json:"options"`
	Answer           string         `json:"answer"`
	Explanation      string         `json:"explanation"`
	Difficulty       int64          `json:"difficulty"`
	Tags             string         `json:"tags"`
	SourceQuote      string         `json:"source_quote"`
	Status           string         `json:"status"`
	ReviewNote       string         `json:"review_note"`
	ContentHash      string         `json:"content_hash"`
	GenModel         string         `json:"gen_model"`
	GenPromptVersion string         `json:"gen_prompt_version"`
	FlagCount        int64          `json:"flag_count"`
	SyncSeq          sql.NullInt64  `json:"sync_seq"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
}

type QuestionFlag struct {
	ID         string        `json:"id"`
	QuestionID string        `json:"question_id"`
	Reason     string        `json:"reason"`
	CreatedAt  int64         `json:"created_at"`
	ResolvedAt sql.NullInt64 `json:"resolved_at"`
}

type QuestionState struct {
	QuestionID string         `json:"question_id"`
	Fsrs       sql.NullString `json:"fsrs"`
	DueAt      sql.NullInt64  `json:"due_at"`
	Favorite   int64          `json:"favorite"`
	WrongCount int64          `json:"wrong_count"`
	UpdatedAt  int64          `json:"updated_at"`
	SyncSeq    int64          `json:"sync_seq"`
}

type QuizSession struct {
	Scope     string         `json:"scope"`
	Data      sql.NullString `json:"data"`
	UpdatedAt int64          `json:"updated_at"`
	DeviceID  string         `json:"device_id"`
	SyncSeq   int64          `json:"sync_seq"`
}

type SyncCounter struct {
	ID    int64 `json:"id"`
	Value int64 `json:"value"`
}
