// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: question.sql

package store

import (
	"context"
	"database/sql"
)

const countQuestions = `-- name: CountQuestions :one
SELECT COUNT(*) FROM question q
LEFT JOIN chunk c ON c.id = q.chunk_id
WHERE (q.status = ?1 OR (?1 IS NULL AND q.status <> 'draft'))
  AND (?2 = 0 OR q.gen_prompt_version LIKE 'agent.%')
  AND (?3 IS NULL OR q.bank_id = ?3)
  AND (?4 IS NULL OR c.document_id = ?4)
  AND (?5 = 0 OR q.flag_count > 0)
  AND (?6 IS NULL
       OR instr(lower(q.stem), lower(?6)) > 0
       OR instr(lower(q.options), lower(?6)) > 0
       OR instr(lower(q.explanation), lower(?6)) > 0)
`

type CountQuestionsParams struct {
	Status     sql.NullString `json:"status"`
	AgentOnly  interface{}    `json:"agent_only"`
	BankID     interface{}    `json:"bank_id"`
	DocumentID interface{}    `json:"document_id"`
	Flagged    interface{}    `json:"flagged"`
	Search     interface{}    `json:"search"`
}

// Assistant drafts belong to a chat until accepted, so they are listed only when asked for by status.
func (q *Queries) CountQuestions(ctx context.Context, arg CountQuestionsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countQuestions,
		arg.Status,
		arg.AgentOnly,
		arg.BankID,
		arg.DocumentID,
		arg.Flagged,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getQuestion = `-- name: GetQuestion :one
SELECT id, bank_id, chunk_id, type, stem, options, answer, explanation, difficulty, tags, source_quote, status, review_note, content_hash, gen_model, gen_prompt_version, flag_count, sync_seq, created_at, updated_at FROM question WHERE id = ?
`

func (q *Queries) GetQuestion(ctx context.Context, id string) (Question, error) {
	row := q.db.QueryRowContext(ctx, getQuestion, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.BankID,
		&i.ChunkID,
		&i.Type,
		&i.Stem,
		&i.Options,
		&i.Answer,
		&i.Explanation,
		&i.Difficulty,
		&i.Tags,
		&i.SourceQuote,
		&i.Status,
		&i.ReviewNote,
		&i.ContentHash,
		&i.GenModel,
		&i.GenPromptVersion,
		&i.FlagCount,
		&i.SyncSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuestionDetail = `-- name: GetQuestionDetail :one
SELECT q.id, q.bank_id, q.chunk_id, q.type, q.stem, q.options, q.answer, q.explanation, q.difficulty, q.tags, q.source_quote, q.status, q.review_note, q.content_hash, q.gen_model, q.gen_prompt_version, q.flag_count, q.sync_seq, q.created_at, q.updated_at,
       COALESCE(c.text, '')         AS chunk_text,
       COALESCE(c.heading_path, '') AS heading_path,
       COALESCE(c.document_id, '')  AS document_id
FROM question q
LEFT JOIN chunk c ON c.id = q.chunk_id
WHERE q.id = ?
`

type GetQuestionDetailRow struct {
	ID               string         `json:"id"`
	BankID           string         `json:"bank_id"`
	ChunkID          sql.NullString `json:"chunk_id"`
	Type             string         `json:"type"`
	Stem             string         `json:"stem"`
	Options          string         `json:"options"`
	Answer           string         `json:"answer"`
	Explanation      string         `json:"explanation"`
	Difficulty       int64          `json:"difficulty"`
	Tags             string         `json:"tags"`
	SourceQuote      string         `json:"source_quote"`
	Status           string         `json:"status"`
	ReviewNote       string         `json:"review_note"`
	ContentHash      string         `json:"content_hash"`
	GenModel         string         `json:"gen_model"`
	GenPromptVersion string         `json:"gen_prompt_version"`
	FlagCount        int64          `json:"flag_count"`
	SyncSeq          sql.NullInt64  `json:"sync_seq"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
	ChunkText        string         `json:"chunk_text"`
	HeadingPath      string         `json:"heading_path"`
	DocumentID       string         `json:"document_id"`
}

func (q *Queries) GetQuestionDetail(ctx context.Context, id string) (GetQuestionDetailRow, error) {
	row := q.db.QueryRowContext(ctx, getQuestionDetail, id)
	var i GetQuestionDetailRow
	err := row.Scan(
		&i.ID,
		&i.BankID,
		&i.ChunkID,
		&i.Type,
		&i.Stem,
		&i.Options,
		&i.Answer,
		&i.Explanation,
		&i.Difficulty,
		&i.Tags,
		&i.SourceQuote,
		&i.Status,
		&i.ReviewNote,
		&i.ContentHash,
		&i.GenModel,
		&i.GenPromptVersion,
		&i.FlagCount,
		&i.SyncSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ChunkText,
		&i.HeadingPath,
		&i.DocumentID,
	)
	return i, err
}

const insertQuestion = `-- name: InsertQuestion :exec
INSERT INTO question (
  id, bank_id, chunk_id, type, stem, options, answer, explanation, difficulty, tags,
  source_quote, status, review_note, content_hash, gen_model, gen_prompt_version,
  created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertQuestionParams struct {
	ID               string         `json:"id"`
	BankID           string         `json:"bank_id"`
	ChunkID          sql.NullString `json:"chunk_id"`
	Type             string         `json:"type"`
	Stem             string         `json:"stem"`
	Options          string         `json:"options"`
	Answer           string         `json:"answer"`
	Explanation      string         `json:"explanation"`
	Difficulty       int64          `json:"difficulty"`
	Tags             string         `json:"tags"`
	SourceQuote      string         `json:"source_quote"`
	Status           string         `json:"status"`
	ReviewNote       string         `json:"review_note"`
	ContentHash      string         `json:"content_hash"`
	GenModel         string         `json:"gen_model"`
	GenPromptVersion string         `json:"gen_prompt_version"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
}

func (q *Queries) InsertQuestion(ctx context.Context, arg InsertQuestionParams) error {
	_, err := q.db.ExecContext(ctx, insertQuestion,
		arg.ID,
		arg.BankID,
		arg.ChunkID,
		arg.Type,
		arg.Stem,
		arg.Options,
		arg.Answer,
		arg.Explanation,
		arg.Difficulty,
		arg.Tags,
		arg.SourceQuote,
		arg.Status,
		arg.ReviewNote,
		arg.ContentHash,
		arg.GenModel,
		arg.GenPromptVersion,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listLiveQuestionsByBank = `-- name: ListLiveQuestionsByBank :many
SELECT id, stem, options, content_hash FROM question
WHERE bank_id = ? AND status NOT IN ('rejected','retired')
`

type ListLiveQuestionsByBankRow struct {
	ID          string `json:"id"`
	Stem        string `json:"stem"`
	Options     string `json:"options"`
	ContentHash string `json:"content_hash"`
}

func (q *Queries) ListLiveQuestionsByBank(ctx context.Context, bankID string) ([]ListLiveQuestionsByBankRow, error) {
	rows, err := q.db.QueryContext(ctx, listLiveQuestionsByBank, bankID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLiveQuestionsByBankRow{}
	for rows.Next() {
		var i ListLiveQuestionsByBankRow
		if err := rows.Scan(
			&i.ID,
			&i.Stem,
			&i.Options,
			&i.ContentHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionIDsByChunk = `-- name: ListQuestionIDsByChunk :many
SELECT id, status FROM question
WHERE chunk_id = ? AND status IN ('published','needs_review','validated')
`

type ListQuestionIDsByChunkRow struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) ListQuestionIDsByChunk(ctx context.Context, chunkID sql.NullString) ([]ListQuestionIDsByChunkRow, error) {
	rows, err := q.db.QueryContext(ctx, listQuestionIDsByChunk, chunkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQuestionIDsByChunkRow{}
	for rows.Next() {
		var i ListQuestionIDsByChunkRow
		if err := rows.Scan(&i.ID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestions = `-- name: ListQuestions :many
SELECT q.id, q.bank_id, q.chunk_id, q.type, q.stem, q.options, q.answer, q.explanation, q.difficulty, q.tags, q.source_quote, q.status, q.review_note, q.content_hash, q.gen_model, q.gen_prompt_version, q.flag_count, q.sync_seq, q.created_at, q.updated_at FROM question q
LEFT JOIN chunk c ON c.id = q.chunk_id
WHERE (q.status = ?1 OR (?1 IS NULL AND q.status <> 'draft'))
  AND (?2 = 0 OR q.gen_prompt_version LIKE 'agent.%')
  AND (?3 IS NULL OR q.bank_id = ?3)
  AND (?4 IS NULL OR c.document_id = ?4)
  AND (?5 = 0 OR q.flag_count > 0)
  AND (?6 IS NULL
       OR instr(lower(q.stem), lower(?6)) > 0
       OR instr(lower(q.options), lower(?6)) > 0
       OR instr(lower(q.explanation), lower(?6)) > 0)
ORDER BY q.created_at DESC, q.id DESC
LIMIT ?8 OFFSET ?7
`

type ListQuestionsParams struct {
	Status     sql.NullString `json:"status"`
	AgentOnly  interface{}    `json:"agent_only"`
	BankID     interface{}    `json:"bank_id"`
	DocumentID interface{}    `json:"document_id"`
	Flagged    interface{}    `json:"flagged"`
	Search     interface{}    `json:"search"`
	PageOffset int64          `json:"page_offset"`
	PageLimit  int64          `json:"page_limit"`
}

// Assistant drafts belong to a chat until accepted, so they are listed only when asked for by status.
func (q *Queries) ListQuestions(ctx context.Context, arg ListQuestionsParams) ([]Question, error) {
	rows, err := q.db.QueryContext(ctx, listQuestions,
		arg.Status,
		arg.AgentOnly,
		arg.BankID,
		arg.DocumentID,
		arg.Flagged,
		arg.Search,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Question{}
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.BankID,
			&i.ChunkID,
			&i.Type,
			&i.Stem,
			&i.Options,
			&i.Answer,
			&i.Explanation,
			&i.Difficulty,
			&i.Tags,
			&i.SourceQuote,
			&i.Status,
			&i.ReviewNote,
			&i.ContentHash,
			&i.GenModel,
			&i.GenPromptVersion,
			&i.FlagCount,
			&i.SyncSeq,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextSyncSeq = `-- name: NextSyncSeq :one
UPDATE sync_counter SET value = value + 1 WHERE id = 1 RETURNING value
`

func (q *Queries) NextSyncSeq(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextSyncSeq)
	var value int64
	err := row.Scan(&value)
	return value, err
}

const questionStatusCounts = `-- name: QuestionStatusCounts :many
SELECT status, COUNT(*) AS n FROM question
WHERE (?1 IS NULL OR bank_id = ?1)
GROUP BY status
`

type QuestionStatusCountsRow struct {
	Status string `json:"status"`
	N      int64  `json:"n"`
}

func (q *Queries) QuestionStatusCounts(ctx context.Context, bankID interface{}) ([]QuestionStatusCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, questionStatusCounts, bankID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuestionStatusCountsRow{}
	for rows.Next() {
		var i QuestionStatusCountsRow
		if err := rows.Scan(&i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setQuestionStatus = `-- name: SetQuestionStatus :exec
UPDATE question
SET status = ?, review_note = ?, sync_seq = ?, updated_at = ?
WHERE id = ?
`

type SetQuestionStatusParams struct {
	Status     string        `json:"status"`
	ReviewNote string        `json:"review_note"`
	SyncSeq    sql.NullInt64 `json:"sync_seq"`
	UpdatedAt  int64         `json:"updated_at"`
	ID         string        `json:"id"`
}

func (q *Queries) SetQuestionStatus(ctx context.Context, arg SetQuestionStatusParams) error {
	_, err := q.db.ExecContext(ctx, setQuestionStatus,
		arg.Status,
		arg.ReviewNote,
		arg.SyncSeq,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateQuestionContent = `-- name: UpdateQuestionContent :exec
UPDATE question
SET type = ?, stem = ?, options = ?, answer = ?, explanation = ?, difficulty = ?, tags = ?,
    content_hash = ?, updated_at = ?
WHERE id = ?
`

type UpdateQuestionContentParams struct {
	Type        string `json:"type"`
	Stem        string `json:"stem"`
	Options     string `json:"options"`
	Answer      string `json:"answer"`
	Explanation string `json:"explanation"`
	Difficulty  int64  `json:"difficulty"`
	Tags        string `json:"tags"`
	ContentHash string `json:"content_hash"`
	UpdatedAt   int64  `json:"updated_at"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateQuestionContent(ctx context.Context, arg UpdateQuestionContentParams) error {
	_, err := q.db.ExecContext(ctx, updateQuestionContent,
		arg.Type,
		arg.Stem,
		arg.Options,
		arg.Answer,
		arg.Explanation,
		arg.Difficulty,
		arg.Tags,
		arg.ContentHash,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
