// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync.sql

package store

import (
	"context"
	"database/sql"
	"strings"
)

const bumpQuestionFlag = `-- name: BumpQuestionFlag :one
UPDATE question SET flag_count = flag_count + 1, updated_at = ?
WHERE id = ? AND status = 'published'
RETURNING flag_count
`

type BumpQuestionFlagParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) BumpQuestionFlag(ctx context.Context, arg BumpQuestionFlagParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, bumpQuestionFlag, arg.UpdatedAt, arg.ID)
	var flag_count int64
	err := row.Scan(&flag_count)
	return flag_count, err
}

const currentSyncSeq = `-- name: CurrentSyncSeq :one
SELECT value FROM sync_counter WHERE id = 1
`

func (q *Queries) CurrentSyncSeq(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, currentSyncSeq)
	var value int64
	err := row.Scan(&value)
	return value, err
}

const insertAttempt = `-- name: InsertAttempt :execrows
INSERT INTO attempt (id, question_id, device_id, answer, is_correct, duration_ms, review_ms, answered_at, received_at, sync_seq)
SELECT ?1, q.id, ?2, ?3, ?4,
       ?5, ?6, ?7, ?8, ?9
FROM question q WHERE q.id = ?10
ON CONFLICT(id) DO UPDATE SET review_ms = excluded.review_ms, sync_seq = excluded.sync_seq
WHERE excluded.review_ms > COALESCE(attempt.review_ms, 0)
`

type InsertAttemptParams struct {
	ID         string        `json:"id"`
	DeviceID   string        `json:"device_id"`
	Answer     string        `json:"answer"`
	IsCorrect  int64         `json:"is_correct"`
	DurationMs sql.NullInt64 `json:"duration_ms"`
	ReviewMs   sql.NullInt64 `json:"review_ms"`
	AnsweredAt int64         `json:"answered_at"`
	ReceivedAt int64         `json:"received_at"`
	SyncSeq    int64         `json:"sync_seq"`
	QuestionID string        `json:"question_id"`
}

// Attempts are append-only except review_ms, which grows when the learner keeps reading
// after answering. A re-upload with a larger review_ms raises it (and re-publishes the row
// to the other devices); anything else is a no-op.
func (q *Queries) InsertAttempt(ctx context.Context, arg InsertAttemptParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertAttempt,
		arg.ID,
		arg.DeviceID,
		arg.Answer,
		arg.IsCorrect,
		arg.DurationMs,
		arg.ReviewMs,
		arg.AnsweredAt,
		arg.ReceivedAt,
		arg.SyncSeq,
		arg.QuestionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertExam = `-- name: InsertExam :execrows
INSERT INTO exam (id, bank_id, title, finished_at, total, correct, answered, percent, passed,
                  limit_sec, used_ms, device_id, items, sync_seq)
VALUES (?1, ?2, ?3, ?4, ?5,
        ?6, ?7, ?8, ?9,
        ?10, ?11, ?12, ?13, ?14)
ON CONFLICT(id) DO NOTHING
`

type InsertExamParams struct {
	ID         string        `json:"id"`
	BankID     string        `json:"bank_id"`
	Title      string        `json:"title"`
	FinishedAt int64         `json:"finished_at"`
	Total      int64         `json:"total"`
	Correct    int64         `json:"correct"`
	Answered   int64         `json:"answered"`
	Percent    int64         `json:"percent"`
	Passed     int64         `json:"passed"`
	LimitSec   sql.NullInt64 `json:"limit_sec"`
	UsedMs     int64         `json:"used_ms"`
	DeviceID   string        `json:"device_id"`
	Items      string        `json:"items"`
	SyncSeq    int64         `json:"sync_seq"`
}

func (q *Queries) InsertExam(ctx context.Context, arg InsertExamParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertExam,
		arg.ID,
		arg.BankID,
		arg.Title,
		arg.FinishedAt,
		arg.Total,
		arg.Correct,
		arg.Answered,
		arg.Percent,
		arg.Passed,
		arg.LimitSec,
		arg.UsedMs,
		arg.DeviceID,
		arg.Items,
		arg.SyncSeq,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listAttemptsSince = `-- name: ListAttemptsSince :many
SELECT id, question_id, device_id, answer, is_correct, duration_ms, answered_at, received_at, sync_seq, review_ms FROM attempt
WHERE sync_seq > ?1
ORDER BY sync_seq ASC
LIMIT ?2
`

type ListAttemptsSinceParams struct {
	Since     int64 `json:"since"`
	PageLimit int64 `json:"page_limit"`
}

func (q *Queries) ListAttemptsSince(ctx context.Context, arg ListAttemptsSinceParams) ([]Attempt, error) {
	rows, err := q.db.QueryContext(ctx, listAttemptsSince, arg.Since, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attempt{}
	for rows.Next() {
		var i Attempt
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.DeviceID,
			&i.Answer,
			&i.IsCorrect,
			&i.DurationMs,
			&i.AnsweredAt,
			&i.ReceivedAt,
			&i.SyncSeq,
			&i.ReviewMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChunkDocuments = `-- name: ListChunkDocuments :many
SELECT c.id AS chunk_id, d.id AS document_id, d.title AS document_title, d.created_at AS document_created_at
FROM chunk c JOIN document d ON d.id = c.document_id
WHERE c.id IN (/*SLICE:chunk_ids*/?)
`

type ListChunkDocumentsRow struct {
	ChunkID           string `json:"chunk_id"`
	DocumentID        string `json:"document_id"`
	DocumentTitle     string `json:"document_title"`
	DocumentCreatedAt int64  `json:"document_created_at"`
}

// The document (a module / chapter of a bank) each of the given chunks belongs to.
func (q *Queries) ListChunkDocuments(ctx context.Context, chunkIds []string) ([]ListChunkDocumentsRow, error) {
	query := listChunkDocuments
	var queryParams []interface{}
	if len(chunkIds) > 0 {
		for _, v := range chunkIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:chunk_ids*/?", strings.Repeat(",?", len(chunkIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:chunk_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChunkDocumentsRow{}
	for rows.Next() {
		var i ListChunkDocumentsRow
		if err := rows.Scan(
			&i.ChunkID,
			&i.DocumentID,
			&i.DocumentTitle,
			&i.DocumentCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExamsSince = `-- name: ListExamsSince :many
SELECT id, bank_id, title, finished_at, total, correct, answered, percent, passed, limit_sec, used_ms, device_id, items, sync_seq FROM exam
WHERE sync_seq > ?1
ORDER BY sync_seq ASC
LIMIT ?2
`

type ListExamsSinceParams struct {
	Since     int64 `json:"since"`
	PageLimit int64 `json:"page_limit"`
}

func (q *Queries) ListExamsSince(ctx context.Context, arg ListExamsSinceParams) ([]Exam, error) {
	rows, err := q.db.QueryContext(ctx, listExamsSince, arg.Since, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Exam{}
	for rows.Next() {
		var i Exam
		if err := rows.Scan(
			&i.ID,
			&i.BankID,
			&i.Title,
			&i.FinishedAt,
			&i.Total,
			&i.Correct,
			&i.Answered,
			&i.Percent,
			&i.Passed,
			&i.LimitSec,
			&i.UsedMs,
			&i.DeviceID,
			&i.Items,
			&i.SyncSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedQuestionCountsByBank = `-- name: ListPublishedQuestionCountsByBank :many
SELECT bank_id, COUNT(*) AS n FROM question WHERE status = 'published' GROUP BY bank_id
`

type ListPublishedQuestionCountsByBankRow struct {
	BankID string `json:"bank_id"`
	N      int64  `json:"n"`
}

func (q *Queries) ListPublishedQuestionCountsByBank(ctx context.Context) ([]ListPublishedQuestionCountsByBankRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedQuestionCountsByBank)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedQuestionCountsByBankRow{}
	for rows.Next() {
		var i ListPublishedQuestionCountsByBankRow
		if err := rows.Scan(&i.BankID, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuizSessionsSince = `-- name: ListQuizSessionsSince :many
SELECT scope, data, updated_at, device_id, sync_seq FROM quiz_session
WHERE sync_seq > ?1
ORDER BY sync_seq ASC
LIMIT ?2
`

type ListQuizSessionsSinceParams struct {
	Since     int64 `json:"since"`
	PageLimit int64 `json:"page_limit"`
}

func (q *Queries) ListQuizSessionsSince(ctx context.Context, arg ListQuizSessionsSinceParams) ([]QuizSession, error) {
	rows, err := q.db.QueryContext(ctx, listQuizSessionsSince, arg.Since, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuizSession{}
	for rows.Next() {
		var i QuizSession
		if err := rows.Scan(
			&i.Scope,
			&i.Data,
			&i.UpdatedAt,
			&i.DeviceID,
			&i.SyncSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatesSince = `-- name: ListStatesSince :many
SELECT question_id, fsrs, due_at, favorite, wrong_count, updated_at, sync_seq FROM question_state
WHERE sync_seq > ?1
ORDER BY sync_seq ASC
LIMIT ?2
`

type ListStatesSinceParams struct {
	Since     int64 `json:"since"`
	PageLimit int64 `json:"page_limit"`
}

func (q *Queries) ListStatesSince(ctx context.Context, arg ListStatesSinceParams) ([]QuestionState, error) {
	rows, err := q.db.QueryContext(ctx, listStatesSince, arg.Since, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuestionState{}
	for rows.Next() {
		var i QuestionState
		if err := rows.Scan(
			&i.QuestionID,
			&i.Fsrs,
			&i.DueAt,
			&i.Favorite,
			&i.WrongCount,
			&i.UpdatedAt,
			&i.SyncSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncQuestions = `-- name: ListSyncQuestions :many
SELECT id, bank_id, chunk_id, type, stem, options, answer, explanation, difficulty, tags, source_quote, status, review_note, content_hash, gen_model, gen_prompt_version, flag_count, sync_seq, created_at, updated_at FROM question
WHERE sync_seq > ?1
ORDER BY sync_seq ASC
LIMIT ?2
`

type ListSyncQuestionsParams struct {
	Since     sql.NullInt64 `json:"since"`
	PageLimit int64         `json:"page_limit"`
}

func (q *Queries) ListSyncQuestions(ctx context.Context, arg ListSyncQuestionsParams) ([]Question, error) {
	rows, err := q.db.QueryContext(ctx, listSyncQuestions, arg.Since, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Question{}
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.BankID,
			&i.ChunkID,
			&i.Type,
			&i.Stem,
			&i.Options,
			&i.Answer,
			&i.Explanation,
			&i.Difficulty,
			&i.Tags,
			&i.SourceQuote,
			&i.Status,
			&i.ReviewNote,
			&i.ContentHash,
			&i.GenModel,
			&i.GenPromptVersion,
			&i.FlagCount,
			&i.SyncSeq,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertQuestionState = `-- name: UpsertQuestionState :execrows
INSERT INTO question_state (question_id, fsrs, due_at, favorite, wrong_count, updated_at, sync_seq)
SELECT q.id, ?1, ?2, ?3, ?4,
       ?5, ?6
FROM question q WHERE q.id = ?7
ON CONFLICT(question_id) DO UPDATE SET
  fsrs = excluded.fsrs, due_at = excluded.due_at, favorite = excluded.favorite,
  wrong_count = excluded.wrong_count, updated_at = excluded.updated_at, sync_seq = excluded.sync_seq
WHERE excluded.updated_at > question_state.updated_at
`

type UpsertQuestionStateParams struct {
	Fsrs       sql.NullString `json:"fsrs"`
	DueAt      sql.NullInt64  `json:"due_at"`
	Favorite   int64          `json:"favorite"`
	WrongCount int64          `json:"wrong_count"`
	UpdatedAt  int64          `json:"updated_at"`
	SyncSeq    int64          `json:"sync_seq"`
	QuestionID string         `json:"question_id"`
}

func (q *Queries) UpsertQuestionState(ctx context.Context, arg UpsertQuestionStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertQuestionState,
		arg.Fsrs,
		arg.DueAt,
		arg.Favorite,
		arg.WrongCount,
		arg.UpdatedAt,
		arg.SyncSeq,
		arg.QuestionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertQuizSession = `-- name: UpsertQuizSession :execrows
INSERT INTO quiz_session (scope, data, updated_at, device_id, sync_seq)
VALUES (?1, ?2, ?3, ?4, ?5)
ON CONFLICT(scope) DO UPDATE SET
  data = excluded.data, updated_at = excluded.updated_at,
  device_id = excluded.device_id, sync_seq = excluded.sync_seq
WHERE excluded.updated_at > quiz_session.updated_at
`

type UpsertQuizSessionParams struct {
	Scope     string         `json:"scope"`
	Data      sql.NullString `json:"data"`
	UpdatedAt int64          `json:"updated_at"`
	DeviceID  string         `json:"device_id"`
	SyncSeq   int64          `json:"sync_seq"`
}

func (q *Queries) UpsertQuizSession(ctx context.Context, arg UpsertQuizSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertQuizSession,
		arg.Scope,
		arg.Data,
		arg.UpdatedAt,
		arg.DeviceID,
		arg.SyncSeq,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
