// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync.sql

package store

import (
	"context"
	"database/sql"
)

const bumpQuestionFlag = `-- name: BumpQuestionFlag :one
UPDATE question SET flag_count = flag_count + 1, updated_at = ?
WHERE id = ? AND status = 'published'
RETURNING flag_count
`

type BumpQuestionFlagParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) BumpQuestionFlag(ctx context.Context, arg BumpQuestionFlagParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, bumpQuestionFlag, arg.UpdatedAt, arg.ID)
	var flag_count int64
	err := row.Scan(&flag_count)
	return flag_count, err
}

const currentSyncSeq = `-- name: CurrentSyncSeq :one
SELECT value FROM sync_counter WHERE id = 1
`

func (q *Queries) CurrentSyncSeq(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, currentSyncSeq)
	var value int64
	err := row.Scan(&value)
	return value, err
}

const insertAttempt = `-- name: InsertAttempt :execrows
INSERT INTO attempt (id, question_id, device_id, answer, is_correct, duration_ms, answered_at, received_at)
SELECT ?1, q.id, ?2, ?3, ?4,
       ?5, ?6, ?7
FROM question q WHERE q.id = ?8
ON CONFLICT(id) DO NOTHING
`

type InsertAttemptParams struct {
	ID         string        `json:"id"`
	DeviceID   string        `json:"device_id"`
	Answer     string        `json:"answer"`
	IsCorrect  int64         `json:"is_correct"`
	DurationMs sql.NullInt64 `json:"duration_ms"`
	AnsweredAt int64         `json:"answered_at"`
	ReceivedAt int64         `json:"received_at"`
	QuestionID string        `json:"question_id"`
}

func (q *Queries) InsertAttempt(ctx context.Context, arg InsertAttemptParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertAttempt,
		arg.ID,
		arg.DeviceID,
		arg.Answer,
		arg.IsCorrect,
		arg.DurationMs,
		arg.AnsweredAt,
		arg.ReceivedAt,
		arg.QuestionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listPublishedQuestionCountsByBank = `-- name: ListPublishedQuestionCountsByBank :many
SELECT bank_id, COUNT(*) AS n FROM question WHERE status = 'published' GROUP BY bank_id
`

type ListPublishedQuestionCountsByBankRow struct {
	BankID string `json:"bank_id"`
	N      int64  `json:"n"`
}

func (q *Queries) ListPublishedQuestionCountsByBank(ctx context.Context) ([]ListPublishedQuestionCountsByBankRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedQuestionCountsByBank)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedQuestionCountsByBankRow{}
	for rows.Next() {
		var i ListPublishedQuestionCountsByBankRow
		if err := rows.Scan(&i.BankID, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuizSessionsSince = `-- name: ListQuizSessionsSince :many
SELECT scope, data, updated_at, device_id, sync_seq FROM quiz_session
WHERE sync_seq > ?1
ORDER BY sync_seq ASC
LIMIT ?2
`

type ListQuizSessionsSinceParams struct {
	Since     int64 `json:"since"`
	PageLimit int64 `json:"page_limit"`
}

func (q *Queries) ListQuizSessionsSince(ctx context.Context, arg ListQuizSessionsSinceParams) ([]QuizSession, error) {
	rows, err := q.db.QueryContext(ctx, listQuizSessionsSince, arg.Since, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuizSession{}
	for rows.Next() {
		var i QuizSession
		if err := rows.Scan(
			&i.Scope,
			&i.Data,
			&i.UpdatedAt,
			&i.DeviceID,
			&i.SyncSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatesSince = `-- name: ListStatesSince :many
SELECT question_id, fsrs, due_at, favorite, wrong_count, updated_at, sync_seq FROM question_state
WHERE sync_seq > ?1
ORDER BY sync_seq ASC
LIMIT ?2
`

type ListStatesSinceParams struct {
	Since     int64 `json:"since"`
	PageLimit int64 `json:"page_limit"`
}

func (q *Queries) ListStatesSince(ctx context.Context, arg ListStatesSinceParams) ([]QuestionState, error) {
	rows, err := q.db.QueryContext(ctx, listStatesSince, arg.Since, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuestionState{}
	for rows.Next() {
		var i QuestionState
		if err := rows.Scan(
			&i.QuestionID,
			&i.Fsrs,
			&i.DueAt,
			&i.Favorite,
			&i.WrongCount,
			&i.UpdatedAt,
			&i.SyncSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncQuestions = `-- name: ListSyncQuestions :many
SELECT id, bank_id, chunk_id, type, stem, options, answer, explanation, difficulty, tags, source_quote, status, review_note, content_hash, gen_model, gen_prompt_version, flag_count, sync_seq, created_at, updated_at FROM question
WHERE sync_seq > ?1
ORDER BY sync_seq ASC
LIMIT ?2
`

type ListSyncQuestionsParams struct {
	Since     sql.NullInt64 `json:"since"`
	PageLimit int64         `json:"page_limit"`
}

func (q *Queries) ListSyncQuestions(ctx context.Context, arg ListSyncQuestionsParams) ([]Question, error) {
	rows, err := q.db.QueryContext(ctx, listSyncQuestions, arg.Since, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Question{}
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.BankID,
			&i.ChunkID,
			&i.Type,
			&i.Stem,
			&i.Options,
			&i.Answer,
			&i.Explanation,
			&i.Difficulty,
			&i.Tags,
			&i.SourceQuote,
			&i.Status,
			&i.ReviewNote,
			&i.ContentHash,
			&i.GenModel,
			&i.GenPromptVersion,
			&i.FlagCount,
			&i.SyncSeq,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertQuestionState = `-- name: UpsertQuestionState :execrows
INSERT INTO question_state (question_id, fsrs, due_at, favorite, wrong_count, updated_at, sync_seq)
SELECT q.id, ?1, ?2, ?3, ?4,
       ?5, ?6
FROM question q WHERE q.id = ?7
ON CONFLICT(question_id) DO UPDATE SET
  fsrs = excluded.fsrs, due_at = excluded.due_at, favorite = excluded.favorite,
  wrong_count = excluded.wrong_count, updated_at = excluded.updated_at, sync_seq = excluded.sync_seq
WHERE excluded.updated_at > question_state.updated_at
`

type UpsertQuestionStateParams struct {
	Fsrs       sql.NullString `json:"fsrs"`
	DueAt      sql.NullInt64  `json:"due_at"`
	Favorite   int64          `json:"favorite"`
	WrongCount int64          `json:"wrong_count"`
	UpdatedAt  int64          `json:"updated_at"`
	SyncSeq    int64          `json:"sync_seq"`
	QuestionID string         `json:"question_id"`
}

func (q *Queries) UpsertQuestionState(ctx context.Context, arg UpsertQuestionStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertQuestionState,
		arg.Fsrs,
		arg.DueAt,
		arg.Favorite,
		arg.WrongCount,
		arg.UpdatedAt,
		arg.SyncSeq,
		arg.QuestionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertQuizSession = `-- name: UpsertQuizSession :execrows
INSERT INTO quiz_session (scope, data, updated_at, device_id, sync_seq)
VALUES (?1, ?2, ?3, ?4, ?5)
ON CONFLICT(scope) DO UPDATE SET
  data = excluded.data, updated_at = excluded.updated_at,
  device_id = excluded.device_id, sync_seq = excluded.sync_seq
WHERE excluded.updated_at > quiz_session.updated_at
`

type UpsertQuizSessionParams struct {
	Scope     string         `json:"scope"`
	Data      sql.NullString `json:"data"`
	UpdatedAt int64          `json:"updated_at"`
	DeviceID  string         `json:"device_id"`
	SyncSeq   int64          `json:"sync_seq"`
}

func (q *Queries) UpsertQuizSession(ctx context.Context, arg UpsertQuizSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertQuizSession,
		arg.Scope,
		arg.Data,
		arg.UpdatedAt,
		arg.DeviceID,
		arg.SyncSeq,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
